'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Niilo22_Soundboard.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _4a844e45() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_4a844e45", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _982f4917() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_982f4917", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property costarica22() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("costarica22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property distrobat_W0mXHagRTEI() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("distrobat_W0mXHagRTEI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ei_ketään_kiinnosta() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ei_ketään_kiinnosta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property eisaatana22() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("eisaatana22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property harmittaa() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("harmittaa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property kiitosnauruista22() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("kiitosnauruista22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property kirveelläjonneja22() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("kirveelläjonneja22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property koukussa22() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("koukussa22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property lohiolikikala22() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("lohiolikikala22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property meetöihin22() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("meetöihin22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property meikalaisenruokaa22() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("meikalaisenruokaa22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property morjesta22() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("morjesta22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property narukaulaan22() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("narukaulaan22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property niap4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("niap4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property niilo22_ajanrakenne() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("niilo22_ajanrakenne", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Niilo22_ARVASIN() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Niilo22_ARVASIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Niilo22_ja_mielipide_työelämästä() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Niilo22_ja_mielipide_työelämästä", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Niilo22_ja_rintsikat() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Niilo22_ja_rintsikat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Niilo22_Mitä_vittua_tääny_meinaa() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Niilo22_Mitä_vittua_tääny_meinaa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Niilo22_rusinat_vittuilee() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Niilo22_rusinat_vittuilee", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Niilo22_tule_paikanpäälle_jos_uskallat() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Niilo22_tule_paikanpäälle_jos_uskallat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Niilo22_vedähomokäteen() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Niilo22_vedähomokäteen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Niilo22_velat_vanhenee() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Niilo22_velat_vanhenee", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nipa1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nipa1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nipa2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nipa2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nipa3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nipa3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property noupadi22() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("noupadi22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property nukuinonneks22() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("nukuinonneks22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Onkstoinyttodellista22() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Onkstoinyttodellista22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property persikkaparsakki22() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("persikkaparsakki22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property SE_ON_VOI_VOI() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SE_ON_VOI_VOI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property sweetdreams22() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("sweetdreams22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property terkkuja22() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("terkkuja22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Tunteisiin22() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Tunteisiin22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property uusivuosi22() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("uusivuosi22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property yrittäkääjonnetpärjäillä22() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("yrittäkääjonnetpärjäillä22", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
